/*
 * Wallaby.js - v1.0.963
 * https://wallabyjs.com
 * Copyright (c) 2014-2020 Wallaby.js - All Rights Reserved.
 *
 * This source code file is a part of Wallaby.js and is a proprietary (closed source) software.

 * IMPORTANT:
 * Wallaby.js is a tool made by software developers for software developers with passion and love for what we do.
 * Pirating the tool is not only illegal and just morally wrong,
 * it is also unfair to other fellow programmers who are using it legally,
 * and very harmful for the tool and its future.
 */
var tracer=global.$_$tracer,tape,tapeInstalled=!1;try{tape=require("tape"),tapeInstalled=!0}catch(e){tracer.start(function(){tracer.reportGlobalError("tape node module is not found or the version is not supported, missing `npm install tape --save-dev`?\n"+(e.stack||""))}),module.exports={init:function(){return{configure:function(){}}}}}if(tapeInstalled){var testFiles=[],harness=tape.getHarness({exit:!1,objectMode:!0}),results=harness._results;tracer.start(function(){testFiles.forEach(function(e){require(e)});var e=tracer.initialSpecId(),t=global.$_$session,i=!1,n=function(){return t!==global.$_$session},r=function(){i||n()||(i=!0,tracer.complete())},s="undefined"!=typeof setImmediate?setImmediate:process.nextTick,o=function(e){if(!e._only)return e.tests.shift();do{var t=e.tests.shift();if(t&&e._only===t.name)return t}while(0!==e.tests.length)},a=function(t){if(!n()){t._testFile=tracer.entryFile();var i=t._cb;t._cb=function(){tracer.specSyncStart();try{if(!i)throw new Error("Test function is not defined.");i(t)}catch(e){t.fail(e.message,{error:e}),t.end(i?e:null)}finally{tracer.specSyncEnd()}},t.on("prerun",function(){n()||(t._id=++e,t._timeout=t._timeout||1e3,t._time=(new tracer._Date).getTime(),t._log=[],tracer.specStart(t._id,t.name))}),t.on("result",function(e){n()||t._log.push(e)}),t.on("test",function(e){n()||a(e)}),t.once("end",function(){if(!n()){var e=tracer.specEnd(),i=t._skip||t._todo,r=t._skip?"skipped":t._todo?"todo":"executed",s={id:t._id,timeRange:e,name:t.name,suite:[],status:r,time:(new tracer._Date).getTime()-t._time,log:[],hook:!1,testFile:t._testFile};if(!i)for(var o=0,a=t._log.length;o<a;o++){var l=t._log[o];if(s.success=s.success&&l.ok,!l.ok&&l.error){var c={message:l.error.message,stack:l.actual&&l.actual.stack||l.error.stack};l.showDiff="equal"===l.operator||"notEqual"===l.operator||"deepEqual"===l.operator||"deepLooseEqual"===l.operator||"notDeepEqual"===l.operator||"notDeepLooseEqual"===l.operator;var u=l.actual,h=l.expected;tracer.setAssertionData(l,c),"fail"!==l.operator&&"error"!==l.operator&&(c.message="Actual: "+tracer._inspect(u,5)+"\nExpected: "+tracer._inspect(h,5)),s.log.push(c)}}s.log.length||delete s.log,tracer.result(s)}})}},l=function(){for(var e;(e=o(results))&&!n();)if(a(e),e.run(),!e.ended)return e.once("end",function(){!n()&&s(l)});results.emit("done")};tracer.started({total:"unknown number of"}),results.once("done",r),l()}),module.exports={init:function(e){return testFiles=e,tape}}}